import React, { useEffect, useRef, useState } from 'react';
import { useLocation } from 'react-router';
import { RefreshCw, ChevronLeft, ChevronRight, ExternalLink } from 'lucide-react';
import { api, setCSRF, date, label, type Row } from './api';
import { useData, Notice, Badge, Form, Action, Reauth, PageTitle, Stat, SelectField, Loading } from './components/shared';
import { Button } from './components/ui/button';
import { Input } from './components/ui/input';
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from './components/ui/table';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from './components/ui/dialog';

export function Entry({ status, reload }: { status: Row; reload: () => void }) {
  const setup = !status.configured;
  return <main className="entry"><div className="brand">R<span>Remodex</span></div><h1>{setup?'搭建你的私人开发终端':'欢迎回来'}</h1><p>任务留在你的电脑。这里管理身份与加密连接。</p><section className="card">
    <h2>{setup?'初始化服务':'管理员登录'}</h2>
    <Form fields={[...(setup?[{name:'setupToken',title:'单次安装凭据',type:'password'}]:[]),{name:'login',title:'管理员账号'}, {name:'password',title:'管理员密码',type:'password',help:setup?'至少 6 位，包含大小写；建议设置更长的独有密码。':undefined},...(setup?[{name:'origin',title:'公网地址',value:location.origin},{name:'githubClientId',title:'GitHub Client ID'},{name:'githubClientSecret',title:'GitHub Client Secret',type:'password'}]:[])]}
      submit={setup?'创建管理员并继续':'登录'} action={async body=>{const {setupToken,...payload}=body;const result=await api(setup?'setup':'login',payload,undefined,setupToken?{'x-setup-token':setupToken}:undefined);setCSRF(result.csrf);reload();}}/>
    {!setup&&<><div className="separator">或</div><Button asChild><a href="/v1/control/github/start">使用 GitHub 登录</a></Button><p>首次登录需要管理员审核；不会申请仓库权限。</p></>}
    {setup&&<p>OAuth 回调地址：<code>{location.origin}/v1/control/github/callback</code></p>}
  </section></main>;
}
export function Overview() {
  const [revision,setRevision]=useState(0), {data,error,loading}=useData('manage/overview',revision);
  return <><PageTitle title="工作台" description="身份、设备与连接，一目了然。"/><Action run={async()=>setRevision(x=>x+1)}>刷新状态</Action><Notice text={error}/>{loading?<Loading/>:data&&<><div className="stats"><Stat title="运行版本" value={data.version}/><Stat title="服务健康" value={label(data.health)}/><Stat title="设备数量" value={data.devices.reduce((n:number,d:Row)=>n+d.count,0)}/><Stat title="在线设备" value={data.live.available?data.live.devices.length:'未取得实时信号'}/></div><section className="card"><h2>账号与设备</h2><div className="flexrow">{data.accounts.map((row:Row)=><div key={row.status}><Badge value={row.status}/> {row.count} 个账号</div>)}</div><p>服务健康不等于客户端加密通道已通过验收。系统睡眠后设备将不可达。</p></section></>}</>;
}
export function Listing({kind}:{kind:'accounts'|'devices'|'phones'|'audit'}) {
  const [page,setPage]=useState(1),[q,setQ]=useState(''),[status,setStatus]=useState(''),[revision,setRevision]=useState(0),[detail,setDetail]=useState<Row|null>(null);
  const location=useLocation();
  const detailTrigger=useRef<HTMLButtonElement|null>(null), refreshTrigger=useRef<HTMLButtonElement|null>(null);
  const [from,setFrom]=useState(''),[to,setTo]=useState('');
  const endpoint=kind==='devices'?'device-list':kind, title={accounts:'账号审核',devices:'开发设备',phones:'手机授权',audit:'安全审计'}[kind];
  const range={...(from?{from:String(new Date(from).getTime())}:{}),...(to?{to:String(new Date(to).getTime())}: {})};
  const {data,error,loading}=useData(`manage/${endpoint}?${new URLSearchParams({page:String(page),q,status,...range})}`,revision);
  const refresh=()=>{setRevision(x=>x+1);setDetail(null);};
  return <><Notice text={kind==='devices'?location.state?.activationNotice||'':''} success/><PageTitle title={title} description="所有管理动作均经过服务端授权，设备备注不改变身份。"/>
    {kind==='audit'&&<section className="toolbar"><label>开始时间<Input type="datetime-local" value={from} onChange={e=>{setFrom(e.target.value);setPage(1);}}/></label><label>结束时间<Input type="datetime-local" value={to} onChange={e=>{setTo(e.target.value);setPage(1);}}/></label><label>结果<SelectField value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="">全部结果</option><option value="success">成功</option><option value="failure">失败</option></SelectField></label></section>}
    <div className="toolbar"><Input aria-label="搜索" placeholder={kind==='audit'?'搜索操作类型':'搜索名称或备注'} value={q} onChange={e=>{setQ(e.target.value);setPage(1);}}/>{['accounts','devices'].includes(kind)&&<SelectField aria-label="状态筛选" value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="">全部状态</option>{(kind==='accounts'?['pending','enabled','rejected','disabled']:['active','revoked']).map(s=><option key={s} value={s}>{label(s)}</option>)}</SelectField>}<Button ref={refreshTrigger} onClick={refresh}><RefreshCw className="mr-2 h-4 w-4"/>刷新</Button></div>
    <Notice text={error}/>{loading?<Loading/>:data&&<section className="card table-card"><div className="table-scroll"><Table><TableHeader><TableRow><TableHead>{kind==='audit'?'操作':'名称 / 身份'}</TableHead><TableHead>状态 / 平台</TableHead><TableHead>关联 / 时间</TableHead><TableHead>操作</TableHead></TableRow></TableHeader><TableBody>{data.items.map((row:Row)=><TableRow key={row.id}><TableCell><strong>{row.login||row.remark||row.action||`手机 ${row.id.slice(0,8)}`}</strong><small>{row.owner||row.github_id||row.actor_id||''}</small></TableCell><TableCell><Badge value={row.status||row.platform||'已记录'}/>{kind==='devices'&&<small>{label(row.platform)} · {row.online===null?'在线状态未知':row.online?'在线':'离线'}</small>}</TableCell><TableCell>{kind==='phones'?`${row.devices.length} 台关联设备`:date(row.last_seen||row.at||row.created_at)}</TableCell><TableCell><Button onClick={event=>{detailTrigger.current=event.currentTarget;setDetail(row);}}>查看详情</Button></TableCell></TableRow>)}</TableBody></Table></div>{!data.items.length&&<div className="empty">暂无匹配记录</div>}<footer className="pagination"><span>共 {data.total} 条 · 第 {page} 页</span><Button disabled={page===1} onClick={()=>setPage(p=>p-1)}><ChevronLeft className="mr-1 h-4 w-4"/>上一页</Button><Button disabled={page*data.size>=data.total} onClick={()=>setPage(p=>p+1)}>下一页<ChevronRight className="ml-1 h-4 w-4"/></Button></footer></section>}
    {detail&&<Dialog open onOpenChange={open=>{if(!open)setDetail(null);}}><DialogContent onCloseAutoFocus={event=>{event.preventDefault();(detailTrigger.current?.isConnected?detailTrigger.current:refreshTrigger.current)?.focus();}} className="left-auto right-0 top-0 h-dvh max-w-lg translate-x-0 translate-y-0 overflow-y-auto rounded-none"><DialogHeader><DialogTitle>{detail.remark||detail.login||title}</DialogTitle><DialogDescription>查看授权状态与管理操作详情。</DialogDescription></DialogHeader><dl>{Object.entries(detail).filter(([k,v])=>!['devices','public_key','diagnostic'].includes(k)&&typeof v!=='object').map(([k,v])=><React.Fragment key={k}><dt>{({id:'稳定 ID',account_id:'账号 ID',public_key:'身份公钥',revision:'修订号',system_name:'系统名称',platform:'平台',status:'状态',owner:'归属',login:'账号',github_id:'GitHub ID',device_limit:'设备上限',created_at:'创建时间',last_seen:'最近活动',action:'操作',actor_id:'操作人',target_id:'对象',at:'时间',role:'角色',remark:'备注',phone_id:'手机 ID',pairing_status:'配对状态',online:'在线'} as Row)[k]||k}</dt><dd>{label(v)}</dd></React.Fragment>)}</dl>{kind==='audit'&&detail.diagnostic&&<section className="rounded-lg bg-muted p-4"><h3>诊断详情</h3><pre className="text-xs">{JSON.stringify(JSON.parse(detail.diagnostic),null,2)}</pre></section>}
      {kind==='accounts'&&detail.role!=='admin'&&<Form key={detail.id} fields={[{name:'deviceLimit',title:'设备上限（留空不限）',type:'number',optional:true,value:detail.device_limit??''}]} submit="批准 / 启用并保存限额" action={async b=>{await api('review',{userId:detail.id,status:'enabled',deviceLimit:b.deviceLimit===''?null:Number(b.deviceLimit)});refresh();}}/>}
      {kind==='accounts'&&detail.role!=='admin'&&<div className="flexrow">{['rejected','disabled'].map(s=><Action key={s} danger confirm="将拒绝访问并撤销该账号设备及配对，确定继续？" run={async()=>{await api('review',{userId:detail.id,status:s,deviceLimit:detail.device_limit});refresh();}}>{label(s)}</Action>)}</div>}
      {kind==='devices'&&<><Form key={detail.id} fields={[{name:'remark',title:'设备备注',value:detail.remark}]} submit="保存备注" action={async b=>{await api('device/remark',{...b,deviceId:detail.id,revision:detail.revision});refresh();}}/><Action danger confirm="撤销设备与配对？不会删除电脑代码。" run={async()=>{await api('device/revoke',{deviceId:detail.id});refresh();}}>撤销设备</Action></>}
      {kind==='phones'&&<>{detail.devices.map((d:Row)=><div className="card" key={d.id}>{d.remark} · {label(d.status)}<Action danger confirm="解除此配对？再次使用需扫码。" run={async()=>{await api('manage/pairing/revoke',{phoneId:detail.id,deviceId:d.id});refresh();}}>解除配对</Action></div>)}<Action danger confirm="撤销这台手机的全部访问授权？" run={async()=>{await api('manage/phone/revoke',{phoneId:detail.id});refresh();}}>撤销整台手机</Action></>}
    </DialogContent></Dialog>}
  </>;
}
export function Profile({user,reload}:{user:Row;reload:()=>void}) {
  const [revision,setRevision]=useState(0),{data,error}=useData('manage/sessions',revision);
  return <><PageTitle title="个人中心" description="管理你的身份与浏览器登录；不会退出电脑上的 Codex。"/><section className="card"><h2>{user.login}</h2><p>GitHub ID：{user.github_id||'尚未绑定'}</p><Badge value={user.status}/></section>
    {user.role==='admin'&&<section className="card"><h2>修改管理员密码</h2><p>修改后所有浏览器会话退出，设备和手机保持授权。</p><Form fields={[{name:'oldPassword',title:'原密码',type:'password'},{name:'newPassword',title:'新密码',type:'password',help:'至少 6 位，含大小写英文字母。'},{name:'confirmation',title:'再次输入新密码',type:'password'}]} submit="修改密码并退出登录" action={async b=>{if(b.newPassword!==b.confirmation)throw new Error('两次新密码不一致。');await api('manage/password',{oldPassword:b.oldPassword,newPassword:b.newPassword});reload();}}/></section>}
    <section className="card"><h2>浏览器会话</h2><Notice text={error}/>{data?.map((s:Row)=><div className="session" key={s.id}><span>{s.current?'当前会话':'其他会话'} · {date(s.created_at)}</span><Action run={async()=>{await api('manage/session/revoke',{id:s.id});if(s.current)reload();else setRevision(x=>x+1);}}>退出此会话</Action></div>)}</section></>;
}
export function Settings(){const {data,error}=useData('manage/settings');return <><PageTitle title="系统设置" description="新 OAuth 配置验证成功前，当前配置持续有效。"/><Reauth/><Notice text={error}/>{data&&<section className="card"><Form fields={[{name:'origin',title:'公网地址',value:data.origin,help:'更换地址会影响客户端配置；不会自动修改反向代理。'},{name:'githubClientId',title:'GitHub Client ID',value:data.githubClientId},{name:'githubClientSecret',title:'替换 Client Secret',type:'password',optional:true,help:'留空保留已有 Secret；服务端不返回明文。'}]} submit="保存候选配置并验证 GitHub" action={async b=>{const result=await api('manage/settings/stage',{...b,revision:data.revision});location.assign(result.verifyURL);}}/><p>验证回调暂用当前服务地址：<code>{data.origin}/v1/control/github/callback</code>。更换域名后请同步调整 OAuth 回调配置。</p></section>}</>;}
export function Updates(){const [revision,setRevision]=useState(0);const update=useData('manage/updates',revision),backups=useData('manage/backups',revision);useEffect(()=>{const timer=setInterval(()=>setRevision(x=>x+1),10000);return()=>clearInterval(timer);},[]);const refresh=()=>setRevision(x=>x+1);return <><PageTitle title="更新与备份" description="只检查正式 Release。安装由你确认，失败保留回滚证据。"/><Reauth/><Notice text={update.error||backups.error}/><section className="card"><h2>服务更新</h2><p>更新会短暂断开手机连接，电脑任务继续执行。</p>{update.data?.available===false?<Notice text="独立更新执行器尚未连接，当前服务不会被修改。"/>:<><p>当前阶段：{label(update.data?.phase)} · 最近检查：{date(update.data?.checkedAt)}</p><Notice text={update.data?.error||''}/><p>目标版本：{update.data?.candidate?.version||'暂无可用正式版本'}</p><pre>{update.data?.candidate?.notes||''}</pre><div className="flexrow"><Action run={async()=>{await api('manage/updates/check',{});refresh();}}>立即检查</Action>{update.data?.candidate&&<Action confirm="将备份数据库并安装此正式版本，连接会短暂中断。继续？" run={async()=>{await api('manage/updates/install',{version:update.data.candidate.version});refresh();}}>备份并安装</Action>}</div></>}</section><section className="card"><h2>一致性备份</h2><Action run={async()=>{await api('manage/backups/create',{});refresh();}}>创建加密备份</Action>{backups.data?.items?.map((b:Row)=><div className="session" key={b.id}><span>{date(b.createdAt)} · {b.version} {b.protected?'· 回滚点':''}</span><Action danger confirm="恢复历史备份将注销会话并撤销旧设备凭据，须重新激活配对。确定？" run={async()=>{await api('manage/backups/restore',{backupId:b.id});refresh();}}>恢复</Action></div>)}<p>默认保留最近 10 份；主密钥需由服务器管理员独立保管。</p></section></>;}
