const test=require('node:test');
const assert=require('node:assert/strict');
const http=require('node:http');
const {randomBytes}=require('node:crypto');
const {ControlStore}=require('./control-store');
const {createControlHTTP}=require('./control-http');
test('management HTTP enforces session, CSRF, ownership and password logout',async t=>{
  const store=new ControlStore({filename:':memory:',masterKey:randomBytes(32)});
  const owner=await store.setup({login:'owner',password:'Abcdef',origin:'https://example.test',githubClientId:'test',githubClientSecret:'not-real'});
  store.githubUser({id:1,login:'owner'},owner.id);
  const normal=store.githubUser({id:2,login:'normal'});store.review(owner,normal.id,'enabled',null);
  const control=createControlHTTP({store,setupToken:randomBytes(32).toString('hex')});
  const server=http.createServer(async(req,res)=>{if(!await control.route(req,res)){res.writeHead(404);res.end();}});
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
  t.after(async()=>{await new Promise(resolve=>server.close(resolve));store.close();});
  const origin=`http://127.0.0.1:${server.address().port}`;
  const get=(path,token)=>fetch(`${origin}/v1/control/${path}`,{headers:{cookie:token?`__Host-remodex=${token}`:''}});
  const post=(path,body,token,csrf)=>fetch(`${origin}/v1/control/${path}`,{method:'POST',headers:{'content-type':'application/json',origin:'https://example.test',cookie:token?`__Host-remodex=${token}`:'','x-csrf-token':csrf||''},body:JSON.stringify(body)});
  assert.equal((await get('manage/accounts')).status,401);
  const adminSession=store.session(owner.id),normalSession=store.session(normal.id);
  assert.equal((await get('manage/accounts',normalSession.token)).status,403);
  assert.equal((await get('manage/accounts',adminSession.token)).status,200);
  const settings=await(await get('manage/settings',adminSession.token)).json();assert.equal(JSON.stringify(settings).includes('not-real'),false);
  const record=store.startActivation({publicKey:randomBytes(32).toString('base64'),platform:'macos',systemName:'Owner device'});store.approveActivation(owner,record.id);
  const devices=await(await get('manage/device-list',normalSession.token)).json();assert.equal(devices.total,0);
  assert.equal((await post('manage/password',{oldPassword:'Abcdef',newPassword:'Xyzabc'},adminSession.token,'wrong')).status,403);
  assert.equal((await post('manage/password',{oldPassword:'Abcdef',newPassword:'Xyzabc'},adminSession.token,adminSession.csrf)).status,200);
  assert.equal((await get('me',adminSession.token)).status,401);
  assert.equal((await get('me',normalSession.token)).status,200);
  const login=await post('login',{login:'owner',password:'Xyzabc'});assert.equal(login.status,200);
  assert.match(login.headers.get('set-cookie'),/Secure; HttpOnly/);
});
